# Use root/example as user/password credentials
version: '3.1'

services:
#  currencyapi:
#    container_name: currency-api
#    restart: always
#    ports:
#      - "5001:5000"

  rdb:
    image: redis:latest
    container_name: rdb-test
    restart: always
    ports:
      - "6379:6379"

  db:
    image: mysql:latest
    container_name: mysql-test
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
#    volumes:
#      - dbdata:/var/lib/mysql  # hz
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: test-db
      MYSQL_USER: apiadmin
      MYSQL_PASSWORD: adminpwd
    ports:
      - "33061:3306"