# Use root/example as user/password credentials
version: '3.1'

services:
#  currencyapi:
#    container_name: currency-api
#    restart: always
#    ports:
#      - "5001:5000"

  redis-db:
    image: redis-with-pass
    container_name: rdb-test
    restart: always
    volumes:
      - ~/DocekrTestVolumes/redis-db:/data
    ports:
      - "6379:6379"

  mysql-db:
    image: mysql:latest
    container_name: mysql-test
    restart: always
    volumes:
      - ~/DocekrTestVolumes/mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: test-db
      MYSQL_USER: apiadmin
      MYSQL_PASSWORD: adminpwd
    ports:
      - "33061:3306"